export type StockRegion = "US" | "KR";

export type StockCatalogEntry = {
  region: StockRegion;
  name: string;
  referenceSymbol?: string;
};

const US_SYMBOLS = `
TSLA INTC HOOD MSTR AMZN CRCL COIN PLTR EWY EWJ PAYP META NVDA GOOGL QQQ SPY
AAPL TSM MU SNDK MSFT AVGO BABA AMD QCOM USAR LITE ORCL DIS UBER CSCO HD SOXL
MRVL CRWV WMT JPM V BRKB FLNC DRAM RKLB CBRS SPCX NBIS WDC ARM BE COHR QNTX
LLY NVO BBX NOK EWT ASTS DELL IBM NOW CRM IREN ONDS BX HPE AMAT CRWD CRDO AAOI
IWM AXTI NFLX COST URNM HIMS EBAY ZM DKNG RIVN GME XLE EWZ BMNR UVXY ADBE GLW
STXX ASML LRCX KLAC ALAB SMCI CIEN KORU SONY MVLL TQQQ SQQQ STRC CAT TXN FLEX
TER TTWO KSTR BSP BOT WEN INTW SNXX XBI BNC FWDI GEV VRT SNOW APP SKHY MUU
SOXS TZA SHAZ SOFI PANW PENG TMF TBT BITO PYPL GS SMH KO RDDT
GDX NET VST SHOP LYTE FUTU JD OUST ISRG ADI PDD MOONSHOT DDOG ANET CXMT UNITREE
MRNA TEM MRK MNST PURR
`.trim().split(/\s+/);

export const KRX_SYMBOLS: Record<string, string> = {
  SKHYNIX: "000660",
  SAMSUNG: "005930",
  HYUNDAI: "005380",
  SAMSUNGEM: "009150",
  HANMI: "042700",
  LGELECTRONICS: "066570",
  NAVER: "035420",
  KODEX200: "069500",
  DOOSBOT: "454910",
  DOOSENER: "034020",
  SKSQUARE: "402340",
  HPSP: "403870",
  JUSUNG: "036930",
};

const KR_SYMBOLS = Object.keys(KRX_SYMBOLS);

const NAMES: Record<string, string> = {
  TSLA: "特斯拉",
  INTC: "英特尔",
  HOOD: "Robinhood",
  MSTR: "Strategy（原微策略）",
  AMZN: "亚马逊",
  CRCL: "Circle",
  COIN: "Coinbase",
  PLTR: "Palantir",
  EWY: "iShares 韩国 ETF",
  EWJ: "iShares 日本 ETF",
  PAYP: "PayPay Corporation",
  META: "Meta Platforms",
  NVDA: "英伟达",
  GOOGL: "谷歌 A",
  QQQ: "纳斯达克 100 ETF",
  SPY: "标普 500 ETF",
  AAPL: "苹果",
  TSM: "台积电",
  MU: "美光科技",
  SNDK: "闪迪",
  MSFT: "微软",
  AVGO: "博通",
  BABA: "阿里巴巴",
  AMD: "超微半导体",
  QCOM: "高通",
  USAR: "USA Rare Earth",
  LITE: "Lumentum",
  ORCL: "甲骨文",
  DIS: "迪士尼",
  UBER: "优步",
  CSCO: "思科",
  HD: "家得宝",
  SOXL: "半导体三倍做多 ETF",
  MRVL: "迈威尔科技",
  CRWV: "CoreWeave",
  WMT: "沃尔玛",
  JPM: "摩根大通",
  V: "维萨",
  BRKB: "伯克希尔·哈撒韦 B",
  FLNC: "Fluence Energy",
  DRAM: "DRAM 主题合约",
  RKLB: "Rocket Lab",
  CBRS: "CBRS 主题合约",
  SPCX: "SPCX 主题合约",
  NBIS: "Nebius",
  WDC: "西部数据",
  ARM: "Arm Holdings",
  BE: "Bloom Energy",
  COHR: "Coherent",
  QNTX: "Qnity Electronics",
  LLY: "礼来",
  NVO: "诺和诺德",
  BBX: "BBX Capital",
  NOK: "诺基亚",
  EWT: "iShares 台湾 ETF",
  ASTS: "AST SpaceMobile",
  DELL: "戴尔科技",
  IBM: "IBM",
  NOW: "ServiceNow",
  CRM: "赛富时",
  IREN: "IREN",
  ONDS: "Ondas Holdings",
  BX: "黑石集团",
  HPE: "慧与科技",
  AMAT: "应用材料",
  CRWD: "CrowdStrike",
  CRDO: "Credo Technology",
  AAOI: "Applied Optoelectronics",
  IWM: "罗素 2000 ETF",
  AXTI: "AXT",
  NFLX: "奈飞",
  COST: "开市客",
  URNM: "铀矿 ETF",
  HIMS: "Hims & Hers",
  EBAY: "eBay",
  ZM: "Zoom",
  DKNG: "DraftKings",
  RIVN: "Rivian",
  GME: "游戏驿站",
  XLE: "能源精选行业 ETF",
  EWZ: "iShares 巴西 ETF",
  BMNR: "BitMine Immersion",
  UVXY: "短期期货波动率 ETF",
  ADBE: "Adobe",
  GLW: "康宁",
  STXX: "STXX 主题合约",
  ASML: "阿斯麦",
  LRCX: "泛林集团",
  KLAC: "科磊",
  ALAB: "Astera Labs",
  SMCI: "超微电脑",
  CIEN: "Ciena",
  KORU: "韩国三倍做多 ETF",
  SONY: "索尼",
  MVLL: "MVLL 主题合约",
  TQQQ: "纳斯达克 100 三倍做多 ETF",
  SQQQ: "纳斯达克 100 三倍做空 ETF",
  STRC: "Strategy 优先股",
  CAT: "卡特彼勒",
  TXN: "德州仪器",
  FLEX: "伟创力",
  TER: "泰瑞达",
  TTWO: "Take-Two Interactive",
  KSTR: "KSTR 主题合约",
  BSP: "BSP 主题合约",
  BOT: "BOT 主题合约",
  WEN: "温蒂汉堡",
  INTW: "INTW 主题合约",
  SNXX: "SNXX 主题合约",
  XBI: "标普生物科技 ETF",
  BNC: "BNC 主题合约",
  FWDI: "FWDI 主题合约",
  GEV: "GE Vernova",
  VRT: "维谛技术",
  SNOW: "Snowflake",
  APP: "AppLovin",
  SKHY: "SKHY 主题合约",
  MUU: "MUU 主题合约",
  SOXS: "半导体三倍做空 ETF",
  TZA: "罗素 2000 三倍做空 ETF",
  SHAZ: "SHAZ 主题合约",
  SOFI: "SoFi",
  PANW: "Palo Alto Networks",
  PENG: "Penguin Solutions",
  TMF: "20 年期美债三倍做多 ETF",
  TBT: "20 年期美债两倍做空 ETF",
  BITO: "ProShares 比特币策略 ETF",
  PYPL: "PayPal",
  GS: "高盛",
  SMH: "VanEck 半导体 ETF",
  KO: "可口可乐",
  RDDT: "Reddit",
  GDX: "VanEck 金矿股 ETF",
  NET: "Cloudflare",
  VST: "Vistra",
  SHOP: "Shopify",
  LYTE: "Lyten 主题合约",
  FUTU: "富途控股",
  JD: "京东",
  OUST: "Ouster",
  ISRG: "直觉外科",
  ADI: "亚德诺半导体",
  PDD: "拼多多",
  MOONSHOT: "Moonshot 主题合约",
  DDOG: "Datadog",
  ANET: "Arista Networks",
  CXMT: "长鑫存储主题合约",
  UNITREE: "宇树科技主题合约",
  MRNA: "Moderna",
  TEM: "Tempus AI",
  MRK: "默沙东",
  MNST: "Monster Beverage",
  PURR: "Hyperliquid Strategies",
  SKHYNIX: "SK 海力士",
  SAMSUNG: "三星电子",
  HYUNDAI: "现代汽车",
  SAMSUNGEM: "三星电机",
  HANMI: "韩美半导体",
  LGELECTRONICS: "LG 电子",
  NAVER: "NAVER",
  KODEX200: "KODEX 200 ETF",
  DOOSBOT: "斗山机器人",
  DOOSENER: "斗山能源",
  SKSQUARE: "SK Square",
  HPSP: "HPSP",
  JUSUNG: "周星工程",
};

export const STOCK_CATALOG: Record<string, StockCatalogEntry> = Object.fromEntries([
  ...US_SYMBOLS.map((symbol) => [symbol, { region: "US" as const, name: NAMES[symbol] ?? `${symbol} 股票` }]),
  ...KR_SYMBOLS.map((symbol) => [symbol, {
    region: "KR" as const,
    name: NAMES[symbol] ?? `${symbol} 股票`,
    referenceSymbol: KRX_SYMBOLS[symbol],
  }]),
]);
